build-client:
    stage: build
    image: docker:latest
    before_script:
    script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker build -t soundtrack-guesser/client:latest
        - docker tag soundtrack-guesser/client:latest soundtrack-guesser/client:${CI_COMMIT_SHORT_SHA}
        - docker push soundtrack-guesser/client:latest
        - docker push soundtrack-guesser/client:${CI_COMMIT_SHORT_SHA}
