version: '3.8'
services:
  db:
    build: ./database
  client:
    build:
      context: ./frontend
    ports:
      - '80:80'
  server:
    build:
      context: ./backend
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/songguesser
    links:
      - 'db'
