version: '2'
services:
  db:
    build: ./database
    # ports:
    #   - '3306:3306'
    volumes:
      - data:/var/lib/mysql
  client:
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_PORT: 8082
    ports:
      - '80:80'
  server:
    build:
      context: ./backend
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/soundtrack_guesser
    links:
      - 'db'
volumes:
  data:
