version: '2'
services:
  db:
    build: ./database
    ports:
      - '3306:3306'
  client:
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_PORT: 8082
    ports:
      - '83:80'
  server:
    build:
      context: ./backend
    ports:
      - '8083:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/soundtrack_guesser
    links:
      - 'db'

